MONGODB_HOST: mongodb-{{ env }}.devops550.online
REDIS_HOST: redis-{{ env }}.devops550.online
MYSQL_HOST: mysql-{{ env }}.devops550.online
RABBITMQ_HOST: rabbitmq-{{ env }}.devops550.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devops550.online
USER_HOST: user.backend-alb-{{ env }}.devops550.online
CART_HOST: cart.backend-alb-{{ env }}.devops550.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devops550.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.devops550.online
